// S-S-M.RO — PDF Header & Footer utilities
// Compatible with jsPDF
// Provides standardized header and footer for all PDF documents

import type jsPDF from 'jspdf'

export interface OrganizationInfo {
  name: string
  cui: string | null
  address: string | null
  logoUrl?: string | null
}

export interface HeaderOptions {
  organization: OrganizationInfo
  pageWidth: number
  marginTop?: number
  fontSize?: number
  lineHeight?: number
}

export interface FooterOptions {
  pageWidth: number
  pageHeight: number
  pageNumber: number
  totalPages?: number
  marginBottom?: number
  fontSize?: number
  generatedDate?: Date
}

/**
 * Adds a standardized header to a PDF page
 *
 * @param doc - jsPDF document instance
 * @param options - Header configuration options
 * @returns The Y position where content should start (after header)
 */
export function addPdfHeader(
  doc: jsPDF,
  options: HeaderOptions
): number {
  const {
    organization,
    pageWidth,
    marginTop = 15,
    fontSize = 10,
    lineHeight = 5
  } = options

  let currentY = marginTop

  // Set font for header
  doc.setFontSize(fontSize)
  doc.setTextColor(60, 60, 60) // Dark gray

  // Company name - bold
  doc.setFont('helvetica', 'bold')
  doc.text(organization.name, 15, currentY)
  currentY += lineHeight

  // CUI (tax ID)
  doc.setFont('helvetica', 'normal')
  if (organization.cui) {
    doc.text(`CUI: ${organization.cui}`, 15, currentY)
    currentY += lineHeight
  }

  // Address
  if (organization.address) {
    const addressLines = doc.splitTextToSize(organization.address, pageWidth - 30)
    doc.text(addressLines, 15, currentY)
    currentY += lineHeight * addressLines.length
  }

  // Horizontal line separator
  currentY += 3
  doc.setDrawColor(200, 200, 200) // Light gray
  doc.setLineWidth(0.5)
  doc.line(15, currentY, pageWidth - 15, currentY)
  currentY += 8

  return currentY
}

/**
 * Adds a standardized footer to a PDF page
 *
 * @param doc - jsPDF document instance
 * @param options - Footer configuration options
 */
export function addPdfFooter(
  doc: jsPDF,
  options: FooterOptions
): void {
  const {
    pageWidth,
    pageHeight,
    pageNumber,
    totalPages,
    marginBottom = 15,
    fontSize = 8,
    generatedDate = new Date()
  } = options

  const footerY = pageHeight - marginBottom

  // Set font for footer
  doc.setFontSize(fontSize)
  doc.setTextColor(100, 100, 100) // Medium gray
  doc.setFont('helvetica', 'normal')

  // Horizontal line separator
  doc.setDrawColor(200, 200, 200) // Light gray
  doc.setLineWidth(0.5)
  doc.line(15, footerY - 5, pageWidth - 15, footerY - 5)

  // Left side: Generated by s-s-m.ro
  const leftText = 'Generat cu s-s-m.ro'
  doc.text(leftText, 15, footerY)

  // Center: Generation date
  const dateText = `Data generării: ${formatDate(generatedDate)}`
  const dateTextWidth = doc.getTextWidth(dateText)
  doc.text(dateText, (pageWidth - dateTextWidth) / 2, footerY)

  // Right side: Page number
  const pageText = totalPages
    ? `Pagina ${pageNumber} din ${totalPages}`
    : `Pagina ${pageNumber}`
  const pageTextWidth = doc.getTextWidth(pageText)
  doc.text(pageText, pageWidth - 15 - pageTextWidth, footerY)
}

/**
 * Adds both header and footer to a PDF page
 *
 * @param doc - jsPDF document instance
 * @param headerOptions - Header configuration
 * @param footerOptions - Footer configuration
 * @returns The Y position where content should start
 */
export function addPdfHeaderAndFooter(
  doc: jsPDF,
  headerOptions: HeaderOptions,
  footerOptions: FooterOptions
): number {
  addPdfFooter(doc, footerOptions)
  return addPdfHeader(doc, headerOptions)
}

/**
 * Formats a date for Romanian locale (DD.MM.YYYY HH:MM)
 */
function formatDate(date: Date): string {
  const day = date.getDate().toString().padStart(2, '0')
  const month = (date.getMonth() + 1).toString().padStart(2, '0')
  const year = date.getFullYear()
  const hours = date.getHours().toString().padStart(2, '0')
  const minutes = date.getMinutes().toString().padStart(2, '0')

  return `${day}.${month}.${year} ${hours}:${minutes}`
}

/**
 * Helper to get content area boundaries (accounting for header and footer)
 *
 * @param pageWidth - PDF page width
 * @param pageHeight - PDF page height
 * @param headerHeight - Height reserved for header (from addPdfHeader return value)
 * @param marginBottom - Bottom margin (footer area)
 * @returns Object with usable content area boundaries
 */
export function getContentArea(
  pageWidth: number,
  pageHeight: number,
  headerHeight: number,
  marginBottom: number = 15
): {
  startX: number
  startY: number
  endX: number
  endY: number
  width: number
  height: number
} {
  const startX = 15
  const startY = headerHeight
  const endX = pageWidth - 15
  const endY = pageHeight - marginBottom - 10 // Extra space for footer line

  return {
    startX,
    startY,
    endX,
    endY,
    width: endX - startX,
    height: endY - startY
  }
}

/**
 * Helper to check if there's enough space for content on current page
 *
 * @param currentY - Current Y position
 * @param requiredHeight - Height needed for content
 * @param contentArea - Content area from getContentArea
 * @returns true if content fits, false if new page needed
 */
export function hasSpaceForContent(
  currentY: number,
  requiredHeight: number,
  contentArea: ReturnType<typeof getContentArea>
): boolean {
  return (currentY + requiredHeight) <= contentArea.endY
}
