// app/api/near-miss/route.ts
// Near-Miss Reporting API: List and create near-miss incident reports

import { NextRequest, NextResponse } from 'next/server'
import { createSupabaseServer } from '@/lib/supabase/server'

// ============================================================
// GET /api/near-miss - List near-miss reports
// ============================================================

export async function GET(request: NextRequest) {
  try {
    const supabase = await createSupabaseServer()

    // Get current user
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Parse query parameters
    const searchParams = request.nextUrl.searchParams
    const organizationId = searchParams.get('organization_id')
    const status = searchParams.get('status')
    const severity = searchParams.get('severity')
    const category = searchParams.get('category')
    const dateFrom = searchParams.get('date_from')
    const dateTo = searchParams.get('date_to')
    const limit = parseInt(searchParams.get('limit') || '100')
    const offset = parseInt(searchParams.get('offset') || '0')

    // Build query
    let query = supabase
      .from('near_miss_reports')
      .select('*', { count: 'exact' })
      .order('incident_date', { ascending: false })
      .range(offset, offset + limit - 1)

    // Apply filters
    if (organizationId && organizationId !== 'all') {
      query = query.eq('organization_id', organizationId)
    }

    if (status) {
      query = query.eq('status', status)
    }

    if (severity) {
      query = query.eq('potential_severity', severity)
    }

    if (category) {
      query = query.eq('category', category)
    }

    if (dateFrom) {
      query = query.gte('incident_date', dateFrom)
    }

    if (dateTo) {
      query = query.lte('incident_date', dateTo)
    }

    // Execute query
    const { data, error, count } = await query

    if (error) {
      console.error('[API] Near-miss GET error:', error)
      return NextResponse.json(
        { error: 'Failed to fetch near-miss reports', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      reports: data || [],
      count: count || 0,
      limit,
      offset,
    })
  } catch (err: any) {
    console.error('[API] Near-miss GET exception:', err)
    return NextResponse.json(
      { error: 'Internal server error', details: err.message },
      { status: 500 }
    )
  }
}

// ============================================================
// POST /api/near-miss - Create near-miss report
// ============================================================

export async function POST(request: NextRequest) {
  try {
    const supabase = await createSupabaseServer()

    // Get current user
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Parse request body
    const body = await request.json()

    // Validate required fields
    if (!body.organization_id) {
      return NextResponse.json(
        { error: 'organization_id is required' },
        { status: 400 }
      )
    }

    if (!body.reported_by) {
      return NextResponse.json(
        { error: 'reported_by is required' },
        { status: 400 }
      )
    }

    if (!body.incident_date) {
      return NextResponse.json(
        { error: 'incident_date is required' },
        { status: 400 }
      )
    }

    if (!body.location) {
      return NextResponse.json({ error: 'location is required' }, { status: 400 })
    }

    if (!body.description) {
      return NextResponse.json(
        { error: 'description is required' },
        { status: 400 }
      )
    }

    if (!body.potential_severity) {
      return NextResponse.json(
        { error: 'potential_severity is required' },
        { status: 400 }
      )
    }

    if (!body.category) {
      return NextResponse.json({ error: 'category is required' }, { status: 400 })
    }

    // Prepare payload
    const payload = {
      organization_id: body.organization_id,
      report_number: '', // Will be auto-generated by trigger
      reported_by: body.reported_by,
      reported_by_user_id: user.id,
      incident_date: body.incident_date,
      incident_time: body.incident_time || null,
      location: body.location,
      description: body.description,
      potential_severity: body.potential_severity,
      category: body.category,
      witnesses: body.witnesses || [],
      immediate_actions: body.immediate_actions || null,
      root_cause: body.root_cause || null,
      corrective_actions: body.corrective_actions || null,
      responsible_person: body.responsible_person || null,
      deadline: body.deadline || null,
      status: body.status || 'raportat',
      photos_paths: body.photos_paths || [],
      investigation_notes: body.investigation_notes || null,
    }

    // Insert record
    const { data, error } = await supabase
      .from('near_miss_reports')
      .insert([payload])
      .select()
      .single()

    if (error) {
      console.error('[API] Near-miss POST error:', error)
      return NextResponse.json(
        { error: 'Failed to create near-miss report', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json(
      { report: data, message: 'Near-miss report created successfully' },
      { status: 201 }
    )
  } catch (err: any) {
    console.error('[API] Near-miss POST exception:', err)
    return NextResponse.json(
      { error: 'Internal server error', details: err.message },
      { status: 500 }
    )
  }
}
