-- ============================================================================
-- T1_tax_FR_IT_ES_PT_NL_SE_DK_FI_NO_IS.sql
-- Tax info pentru forme juridice din FR, IT, ES, PT, NL, SE, DK, FI, NO, IS
-- Generated: 2026-02-15
-- Agent: Claude Sonnet 4.5
-- ============================================================================

-- Inserează date fiscale pentru formele juridice relevante din 10 țări europene
-- Cotele și plafoanele sunt valabile pentru 2025-2026
-- Moneda locală: EUR pentru FR, IT, ES, PT, NL, FI; SEK pentru SE; DKK pentru DK; NOK pentru NO; ISK pentru IS

-- ============================================================================
-- FRANCE (13 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('FR-SARL', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'IS_normal', ARRAY['IS_normal','IS_PME','micro_BIC','micro_BNC'],
 '25%', NULL, '31.4% flat tax (PFU depuis 01/2026)', '11-45% barème progressif',
 '~45% (charges patronales)', '~22% (charges salariales)',
 '1 EUR (depuis 2023)', false, NULL,
 'Déclaration IS annuelle, TVA mensuelle/trimestrielle, DSN mensuelle',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'SARL: IS 25% standard. PME 15% sur premiers 42500 EUR. PFU dividendes passé de 30% à 31.4% depuis janvier 2026.'),

('FR-EURL', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'IS_ou_IR', ARRAY['IS_normal','IR_BIC','micro_BIC'],
 '25% (si IS)', '11-45% barème (si IR)', '31.4% flat tax (PFU)', '11-45% barème progressif',
 '~45% (patronales)', '~22% (salariales)',
 '1 EUR', false, NULL,
 'Selon régime: IS ou IR (BIC/BNC). DSN si salarié',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'EURL: société unipersonnelle. Choix entre IS et IR. Gérant majoritaire = TNS (cotisations ~45% du revenu).'),

('FR-SAS', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'IS_normal', ARRAY['IS_normal','IS_PME'],
 '25%', NULL, '31.4% flat tax (PFU)', '11-45% barème progressif',
 '~45% (patronales)', '~22% (salariales)',
 '1 EUR (50% libéré)', false, NULL,
 'IS annuelle, TVA, DSN. Président = assimilé salarié',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'SAS: structure souple, IS 25%, PME 15% sur premiers 42500 EUR. Minimum 50% capital libéré à constitution.'),

('FR-SASU', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'IS_normal', ARRAY['IS_normal','IS_PME'],
 '25%', NULL, '31.4% flat tax (PFU)', '11-45% barème progressif',
 '~45% (patronales)', '~22% (salariales)',
 '1 EUR', false, NULL,
 'IS annuelle, TVA, DSN. Président unique = assimilé salarié',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'SASU: SAS unipersonnelle. Avantage: président assimilé salarié (régime général SS). Capital 1 EUR minimum.'),

('FR-SA', 'FR',
 true, 'Pas de seuil franchise', 20, '10%, 5.5%, 2.1%',
 'IS_normal', ARRAY['IS_normal'],
 '25%', NULL, '31.4% flat tax (PFU)', '11-45% barème progressif',
 '~45% (patronales)', '~22% (salariales)',
 '37000 EUR', false, NULL,
 'IS annuelle, TVA obligatoire, DSN, publication comptes annuels',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'SA: forme lourde, capital minimum 37000 EUR, 2-7 administrateurs (conseil) ou directoire + conseil surveillance.'),

('FR-SNC', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'IR_BIC', ARRAY['IR_BIC','IS_option'],
 NULL, '11-45% barème (associés)', NULL, '11-45% barème progressif',
 '~45% TNS si gérant', '~22% (si salarié)',
 'Pas de minimum', false, NULL,
 'IR par défaut (transparence fiscale), TVA selon CA, pas de DSN sauf salariés',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'SNC: société de personnes, responsabilité illimitée, IR transparent. Option IS possible. Associés = TNS.'),

('FR-EI', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'IR_BIC', ARRAY['IR_BIC','IR_BNC','micro_BIC','micro_BNC'],
 NULL, '11-45% barème', NULL, NULL,
 'Variable TNS (RSI/SSI)', 'N/A',
 'N/A', false, NULL,
 'Déclaration 2042-C-PRO, TVA si > seuils, pas de DSN',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'EI: entreprise individuelle, pas de personnalité morale, IR au barème. Régime micro ou réel. TNS: cotisations ~45% du revenu.'),

('FR-MICRO', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, 'Franchise en base (pas de TVA collectée)',
 'micro_BIC', ARRAY['micro_BIC','micro_BNC'],
 NULL, 'Abattement forfaitaire (71% vente, 50% services) puis barème', NULL, NULL,
 'Variable TNS (RSI/SSI)', 'N/A',
 'N/A', false, 'Franchise TVA',
 'Déclaration 2042-C-PRO simplifiée, pas de TVA si < seuil',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'Micro-entreprise: régime ultra-simplifié, franchise TVA, abattement forfaitaire IR. Plafonds 2025: 85000/37500 EUR.'),

('FR-MED', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'BNC', ARRAY['BNC','micro_BNC'],
 NULL, '11-45% barème', NULL, NULL,
 'URSSAF libéral ~45%', 'N/A',
 'N/A', false, NULL,
 'Déclaration 2042-C-PRO (BNC), TVA si > seuil, URSSAF libéral',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'Profession libérale médicale: BNC, URSSAF PAMC/CARMF. IR barème progressif, franchise TVA si < 37500 EUR.'),

('FR-AVOC', 'FR',
 false, '37500 EUR', 20, '10%, 5.5%, 2.1%',
 'BNC', ARRAY['BNC','micro_BNC'],
 NULL, '11-45% barème', NULL, NULL,
 'CNBF (caisse avocats) ~45%', 'N/A',
 'N/A', false, NULL,
 'Déclaration 2042-C-PRO (BNC), TVA si > seuil, CNBF',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'Avocat: profession libérale réglementée, BNC, caisse CNBF. Franchise TVA 37500 EUR services.'),

('FR-ASSOC', 'FR',
 false, 'N/A (sauf activités lucratives)', 20, '10%, 5.5%, 2.1%',
 'Exonération', ARRAY['Exonération','IS_si_lucratif'],
 '0% (si non lucrative)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'N/A', false, 'Loi 1901, exonération fiscale si non lucrative',
 'Aucune si non lucrative. Si lucrative: IS + TVA',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'Association loi 1901: exonérée impôts si non lucrative. Si activités lucratives prépondérantes: IS 25%, TVA.'),

('FR-SCOP', 'FR',
 false, '85000 EUR (vente) / 37500 EUR (services)', 20, '10%, 5.5%, 2.1%',
 'IS_coopératif', ARRAY['IS_coopératif'],
 '25% (avec exonérations partielles)', NULL, '31.4% flat tax (PFU)', '11-45% barème progressif',
 '~45% (patronales)', '~22% (salariales)',
 'Variable selon forme (SARL SCOP: 1 EUR)', false, 'Statut coopératif, exonérations partielles',
 'IS annuelle (exonérations coopératives), TVA, DSN',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'SCOP: société coopérative de production. IS 25% avec exonérations (réserves impartageables). Salariés = associés majoritaires.'),

('FR-EPIC', 'FR',
 true, 'N/A (établissement public)', 20, '10%, 5.5%, 2.1%',
 'IS_public', ARRAY['IS_public'],
 '25% (activités concurrentielles)', NULL, NULL, NULL,
 'N/A (établissement public)', 'N/A',
 'N/A (établissement public)', false, 'Établissement public à caractère industriel et commercial',
 'IS sur activités concurrentielles, TVA obligatoire',
 'DGFiP', 'https://www.impots.gouv.fr',
 '2025-01-01', NULL, '2026-02-15',
 'EPIC: établissement public industriel et commercial. IS 25% sur activités concurrentielles. TVA obligatoire.');

-- ============================================================================
-- ITALY (10 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('IT-SRL', 'IT',
 true, 'Nessuna soglia', 22, '10%, 4%',
 'IRES_IRAP', ARRAY['IRES_IRAP','IRES_premiale_2025'],
 '24% IRES + 3.9% IRAP', NULL, '26%', 'IRPEF 23-43%',
 '29-32% (INPS)', '9.19-10.49% (INPS)',
 '1 EUR', false, 'IRES premiale 20% per FY 2025 (con condizioni)',
 'Dichiarazione annuale IRES/IRAP, IVA mensile/trimestrale, modello 770',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'SRL: IRES 24% + IRAP 3.9%. Mini-IRES 20% per 2025 se 80% utili in riserva + 30% investimenti. Capitale minimo 1 EUR. INPS max cap 120607 EUR (2025).'),

('IT-SRLS', 'IT',
 true, 'Nessuna soglia', 22, '10%, 4%',
 'IRES_IRAP', ARRAY['IRES_IRAP','IRES_premiale_2025'],
 '24% IRES + 3.9% IRAP', NULL, '26%', 'IRPEF 23-43%',
 '29-32% (INPS)', '9.19-10.49% (INPS)',
 '1 EUR (max 9999 EUR)', false, 'SRL semplificata, capitale max 9999 EUR',
 'Dichiarazione IRES/IRAP annuale, IVA, modello 770',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'SRLS: SRL semplificata, capitale 1-9999 EUR versato integralmente. Statuto standard. IRES 24%, IRAP 3.9%. Mini-IRES 20% per 2025.'),

('IT-SPA', 'IT',
 true, 'Nessuna soglia', 22, '10%, 4%',
 'IRES_IRAP', ARRAY['IRES_IRAP'],
 '24% IRES + 3.9% IRAP', NULL, '26%', 'IRPEF 23-43%',
 '29-32% (INPS)', '9.19-10.49% (INPS)',
 '50000 EUR', false, NULL,
 'Dichiarazione IRES/IRAP, IVA, 770, bilancio pubblicato',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'SPA: società per azioni, capitale minimo 50000 EUR. IRES 24%, IRAP 3.9%. Dividendi 26% ritenuta. Bilancio pubblicato obbligatorio.'),

('IT-SNC', 'IT',
 false, 'Nessuna soglia', 22, '10%, 4%',
 'IRPEF_transparente', ARRAY['IRPEF_transparente'],
 NULL, 'IRPEF 23-43% (soci)', NULL, 'IRPEF 23-43%',
 'Variabile (INPS commercianti/artigiani)', 'Variabile',
 'Nessun minimo', false, NULL,
 'Dichiarazione IRPEF soci (trasparenza fiscale), IVA',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'SNC: società in nome collettivo, trasparenza fiscale, responsabilità illimitata solidale. IRPEF barème 23-43%. INPS commercianti.'),

('IT-DITTA', 'IT',
 false, 'Nessuna soglia', 22, '10%, 4%',
 'IRPEF', ARRAY['IRPEF','forfettario'],
 NULL, 'IRPEF 23-43% o 5-15% forfettario', NULL, NULL,
 'INPS artigiani/commercianti ~24%', 'N/A',
 'N/A', false, 'Regime forfettario 5-15% se < 85000 EUR',
 'Dichiarazione IRPEF, IVA (escluso regime forfettario)',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'Ditta individuale: IRPEF 23-43%. Regime forfettario disponibile (5-15%) se fatturato < 85000 EUR. INPS artigiani/commercianti ~24%.'),

('IT-MED', 'IT',
 false, 'Nessuna soglia', 22, '10%, 4%',
 'IRPEF', ARRAY['IRPEF'],
 NULL, 'IRPEF 23-43%', NULL, NULL,
 'Cassa previdenziale ordine (~15-20%)', 'N/A',
 'N/A', false, NULL,
 'Dichiarazione IRPEF, IVA, cassa ordine professionale',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'Professione medica: IRPEF 23-43%, cassa ordine (ENPAM per medici) ~15-20%. IVA 22% o esenzione per alcune prestazioni sanitarie.'),

('IT-AVV', 'IT',
 false, 'Nessuna soglia', 22, '10%, 4%',
 'IRPEF', ARRAY['IRPEF'],
 NULL, 'IRPEF 23-43%', NULL, NULL,
 'Cassa Forense ~15%', 'N/A',
 'N/A', false, NULL,
 'Dichiarazione IRPEF, IVA, Cassa Forense',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'Avvocato: professione liberale, IRPEF 23-43%, Cassa Forense ~15%. IVA 22%, esenzione per alcune prestazioni giudiziarie.'),

('IT-ASSOC', 'IT',
 false, 'N/A (se non commerciale)', 22, '10%, 4%',
 'Esenzione', ARRAY['Esenzione','IRES_se_commerciale'],
 '0% (non commerciale)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'N/A', false, 'Associazione non riconosciuta, esenzione se non commerciale',
 'Nessuna se non commerciale. Se commerciale: IRES + IVA',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'Associazione: esente imposte se non commerciale. Se attività commerciale prevalente: IRES 24%, IRAP 3.9%, IVA.'),

('IT-COOP', 'IT',
 true, 'Nessuna soglia', 22, '10%, 4%',
 'IRES_cooperativa', ARRAY['IRES_cooperativa'],
 '24% IRES + 3.9% IRAP (con agevolazioni)', NULL, '26%', 'IRPEF 23-43%',
 '29-32% (INPS)', '9.19-10.49% (INPS)',
 'Variabile', false, 'Cooperative, agevolazioni fiscali parziali',
 'Dichiarazione IRES/IRAP, IVA, bilancio sociale',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'Cooperativa: IRES 24%, IRAP 3.9% con agevolazioni parziali. Riserve indivisibili. IVA 22%. INPS 29-32% datore, 9-10% dipendente.'),

('IT-ENTEPU', 'IT',
 false, 'N/A', 22, '10%, 4%',
 'Esenzione_pubblico', ARRAY['Esenzione_pubblico','IRES_commerciale'],
 '24% IRES (attività commerciale)', NULL, NULL, NULL,
 'N/A (ente pubblico)', 'N/A',
 'N/A', false, 'Ente pubblico, esenzione salvo attività commerciale',
 'IRES solo su attività commerciale, IVA se applicabile',
 'Agenzia delle Entrate', 'https://www.agenziaentrate.gov.it',
 '2025-01-01', NULL, '2026-02-15',
 'Ente pubblico: esente imposte per attività istituzionale. IRES 24% + IRAP 3.9% su attività commerciale. IVA se dovuta.');

-- ============================================================================
-- SPAIN (7 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('ES-SL', 'ES',
 true, 'Sin umbral', 21, '10%, 4%',
 'IS_general', ARRAY['IS_general','IS_reducido_microempresa','IS_reducido_startup'],
 '25%', NULL, '30%', 'IRPF 19-47%',
 '30.65% + variable AT', '6.48-6.5%',
 '1 EUR (desde 2023)', false, 'Microempresa: 21-22% (2025), 19-21% (2026) primeros 50000 EUR. Startup: 15% primeros 2 años',
 'Declaración IS anual (modelo 200), IVA trimestral, Seguridad Social mensual',
 'AEAT', 'https://sede.agenciatributaria.gob.es',
 '2025-01-01', NULL, '2026-02-15',
 'SL: IS 25% estándar. Microempresa (< 1M EUR): 21% hasta 50k, 22% exceso (2025); 19-21% (2026). Startup: 15% primeros 2 años. IVA 21%, sin umbral.'),

('ES-SLU', 'ES',
 true, 'Sin umbral', 21, '10%, 4%',
 'IS_general', ARRAY['IS_general','IS_reducido_microempresa','IS_reducido_startup'],
 '25%', NULL, '30%', 'IRPF 19-47%',
 '30.65% + variable AT', '6.48-6.5%',
 '1 EUR', false, 'Microempresa: 21-22% (2025), 19-21% (2026). Startup: 15%',
 'Declaración IS (modelo 200), IVA trimestral, Seguridad Social',
 'AEAT', 'https://sede.agenciatributaria.gob.es',
 '2025-01-01', NULL, '2026-02-15',
 'SLU: SL unipersonal, un único socio. IS 25%, reducciones microempresa/startup. Capital mínimo 1 EUR. IVA 21%, sin umbral.'),

('ES-SA', 'ES',
 true, 'Sin umbral', 21, '10%, 4%',
 'IS_general', ARRAY['IS_general'],
 '25%', NULL, '30%', 'IRPF 19-47%',
 '30.65% + variable AT', '6.48-6.5%',
 '60000 EUR', false, NULL,
 'Declaración IS anual, IVA trimestral, cuentas anuales publicadas, Seguridad Social',
 'AEAT', 'https://sede.agenciatributaria.gob.es',
 '2025-01-01', NULL, '2026-02-15',
 'SA: sociedad anónima, capital mínimo 60000 EUR. IS 25%, dividendos 30%. IVA 21%, sin umbral. Obligación publicar cuentas anuales.'),

('ES-AUTONOMO', 'ES',
 true, 'Sin umbral', 21, '10%, 4%',
 'IRPF_estimacion_directa', ARRAY['IRPF_estimacion_directa','IRPF_estimacion_objetiva'],
 NULL, 'IRPF 19-47%', NULL, NULL,
 'Cuota autónomo ~300-400 EUR/mes (Seguridad Social)', 'N/A',
 'N/A', false, 'Sistema cuota fija autónomo (2025-2031: sistema progresivo por ingresos)',
 'Declaración IRPF anual (modelo 100), IVA trimestral (modelos 303/390)',
 'AEAT', 'https://sede.agenciatributaria.gob.es',
 '2025-01-01', NULL, '2026-02-15',
 'Autónomo: IRPF 19-47%. Cuota Seguridad Social fija ~300-400 EUR/mes (sistema progresivo 2025-2031). IVA 21%, sin umbral.'),

('ES-MED', 'ES',
 true, 'Sin umbral', 21, '10%, 4%',
 'IRPF_estimacion_directa', ARRAY['IRPF_estimacion_directa'],
 NULL, 'IRPF 19-47%', NULL, NULL,
 'Cuota autónomo + colegio profesional', 'N/A',
 'N/A', false, NULL,
 'Declaración IRPF (modelo 100), IVA trimestral, colegio médico',
 'AEAT', 'https://sede.agenciatributaria.gob.es',
 '2025-01-01', NULL, '2026-02-15',
 'Médico: profesión liberal, IRPF 19-47%, cuota autónomo SS + colegio profesional. IVA 21% o exento (algunas prestaciones sanitarias).'),

('ES-ASOC', 'ES',
 false, 'N/A (si no lucrativa)', 21, '10%, 4%',
 'Exención', ARRAY['Exención','IS_si_lucrativa'],
 '0% (no lucrativa)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'N/A', false, 'Asociación sin ánimo de lucro, exención fiscal',
 'Ninguna si no lucrativa. Si lucrativa: IS 25% + IVA',
 'AEAT', 'https://sede.agenciatributaria.gob.es',
 '2025-01-01', NULL, '2026-02-15',
 'Asociación: exenta impuestos si no lucrativa. Si actividad lucrativa preponderante: IS 25%, IVA 21%.'),

('ES-COOP', 'ES',
 true, 'Sin umbral', 21, '10%, 4%',
 'IS_cooperativa', ARRAY['IS_cooperativa'],
 '20% (cooperativas protegidas)', NULL, '30%', 'IRPF 19-47%',
 '30.65% + variable AT', '6.48-6.5%',
 'Variable', false, 'Cooperativa protegida: IS 20%',
 'Declaración IS (modelo 200), IVA trimestral, Seguridad Social',
 'AEAT', 'https://sede.agenciatributaria.gob.es',
 '2025-01-01', NULL, '2026-02-15',
 'Cooperativa: IS 20% (protegidas) o 25% (no protegidas). IVA 21%, sin umbral. Seguridad Social estándar. Reservas obligatorias.');

-- ============================================================================
-- PORTUGAL (7 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('PT-LDA', 'PT',
 false, '15000 EUR', 23, '13%, 6%',
 'IRC_normal', ARRAY['IRC_normal','IRC_reduzido_PME'],
 '20% (2025), 19% (2026)', NULL, '28% (25% corporativo)', 'IRS 14.5-48%',
 '23.75%', '11%',
 '1 EUR (desde reforma)', false, 'PME: 16% (2025) ou 15% (2026) primeiros 50000 EUR',
 'Declaração IRC anual, IVA trimestral, Segurança Social mensal',
 'Autoridade Tributária e Aduaneira', 'https://www.portaldasfinancas.gov.pt',
 '2025-01-01', NULL, '2026-02-15',
 'LDA: IRC 20% (2025), 19% (2026). PME: 16%/15% primeiros 50k EUR. Dividendos 28% (pessoa singular). IVA 23%, umbral 15000 EUR. Capital mínimo 1 EUR.'),

('PT-UNIP', 'PT',
 false, '15000 EUR', 23, '13%, 6%',
 'IRC_normal', ARRAY['IRC_normal','IRC_reduzido_PME'],
 '20% (2025), 19% (2026)', NULL, '28% (25% corporativo)', 'IRS 14.5-48%',
 '23.75%', '11%',
 '1 EUR', false, 'PME: 16% (2025) ou 15% (2026) primeiros 50000 EUR',
 'Declaração IRC, IVA trimestral, Segurança Social',
 'Autoridade Tributária e Aduaneira', 'https://www.portaldasfinancas.gov.pt',
 '2025-01-01', NULL, '2026-02-15',
 'UNIP: sociedade unipessoal por quotas (LDA com único sócio). IRC 20%/19%, PME 16%/15% primeiros 50k EUR. Capital mínimo 1 EUR.'),

('PT-SA', 'PT',
 true, 'Sem umbral', 23, '13%, 6%',
 'IRC_normal', ARRAY['IRC_normal'],
 '20% (2025), 19% (2026)', NULL, '28% (25% corporativo)', 'IRS 14.5-48%',
 '23.75%', '11%',
 '50000 EUR', false, NULL,
 'Declaração IRC anual, IVA trimestral, contas anuais publicadas, Segurança Social',
 'Autoridade Tributária e Aduaneira', 'https://www.portaldasfinancas.gov.pt',
 '2025-01-01', NULL, '2026-02-15',
 'SA: sociedade anónima, capital mínimo 50000 EUR (30% liberado à constituição). IRC 20% (2025), 19% (2026). Dividendos 28%. IVA 23%.'),

('PT-ENI', 'PT',
 false, '15000 EUR', 23, '13%, 6%',
 'IRS_categoria_B', ARRAY['IRS_categoria_B','regime_simplificado'],
 NULL, 'IRS 14.5-48%', NULL, NULL,
 'Segurança Social trabalhadores independentes ~21.4% (21.4% base declarada)', 'N/A',
 'N/A', false, 'Regime simplificado: coeficiente 0.75 (despesas forfetárias)',
 'Declaração IRS anual (anexo B), IVA trimestral se aplicável',
 'Autoridade Tributária e Aduaneira', 'https://www.portaldasfinancas.gov.pt',
 '2025-01-01', NULL, '2026-02-15',
 'ENI: empresário em nome individual. IRS categoria B 14.5-48%. Segurança Social independentes ~21.4%. IVA 23%, umbral 15000 EUR.'),

('PT-MED', 'PT',
 false, '15000 EUR', 23, '13%, 6%',
 'IRS_categoria_B', ARRAY['IRS_categoria_B'],
 NULL, 'IRS 14.5-48%', NULL, NULL,
 'Ordem profissional + SS ~21.4%', 'N/A',
 'N/A', false, NULL,
 'Declaração IRS (anexo B), IVA trimestral, Ordem dos Médicos',
 'Autoridade Tributária e Aduaneira', 'https://www.portaldasfinancas.gov.pt',
 '2025-01-01', NULL, '2026-02-15',
 'Médico: profissão liberal, IRS categoria B 14.5-48%, Ordem dos Médicos + SS independentes ~21.4%. IVA 23% ou isento (serviços saúde).'),

('PT-ASOC', 'PT',
 false, 'N/A (se não lucrativa)', 23, '13%, 6%',
 'Isenção', ARRAY['Isenção','IRC_se_lucrativa'],
 '0% (não lucrativa)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'N/A', false, 'Associação sem fins lucrativos, isenção fiscal',
 'Nenhuma se não lucrativa. Se lucrativa: IRC + IVA',
 'Autoridade Tributária e Aduaneira', 'https://www.portaldasfinancas.gov.pt',
 '2025-01-01', NULL, '2026-02-15',
 'Associação: isenta impostos se sem fins lucrativos. Se atividade lucrativa preponderante: IRC 20%/19%, IVA 23%.'),

('PT-COOP', 'PT',
 true, 'Sem umbral', 23, '13%, 6%',
 'IRC_cooperativa', ARRAY['IRC_cooperativa'],
 '20% (2025), 19% (2026) com isenções parciais', NULL, '28%', 'IRS 14.5-48%',
 '23.75%', '11%',
 'Variável', false, 'Cooperativa, isenções fiscais parciais',
 'Declaração IRC, IVA trimestral, relatório atividades, Segurança Social',
 'Autoridade Tributária e Aduaneira', 'https://www.portaldasfinancas.gov.pt',
 '2025-01-01', NULL, '2026-02-15',
 'Cooperativa: IRC 20% (2025), 19% (2026) com isenções parciais. Reservas obrigatórias. IVA 23%. Segurança Social padrão.');

-- ============================================================================
-- NETHERLANDS (7 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('NL-BV', 'NL',
 true, 'Geen drempel', 21, '6%, 0%',
 'Vennootschapsbelasting', ARRAY['Vennootschapsbelasting'],
 '19% tot 200000 EUR, 25.8% boven', NULL, '33% (2025), 36% (vanaf 2025)', 'Box 1: 36.97-49.5%',
 'AWf 2.74-7.74%, max 75864 EUR (2025)', 'Variabel',
 '0.01 EUR', false, NULL,
 'Aangifte VPB jaarlijks, BTW per kwartaal, loonbelasting maandelijks',
 'Belastingdienst', 'https://www.belastingdienst.nl',
 '2025-01-01', NULL, '2026-02-15',
 'BV: besloten vennootschap. VPB 19% tot 200k EUR, 25.8% boven. Dividenden 33% (2025), 36% (vanaf 2025). BTW 21%, geen drempel. Capital €0.01.'),

('NL-NV', 'NL',
 true, 'Geen drempel', 21, '6%, 0%',
 'Vennootschapsbelasting', ARRAY['Vennootschapsbelasting'],
 '19% tot 200000 EUR, 25.8% boven', NULL, '33% (2025), 36% (vanaf 2025)', 'Box 1: 36.97-49.5%',
 'AWf 2.74-7.74%', 'Variabel',
 '45000 EUR', false, NULL,
 'Aangifte VPB, BTW per kwartaal, jaarrekening gepubliceerd',
 'Belastingdienst', 'https://www.belastingdienst.nl',
 '2025-01-01', NULL, '2026-02-15',
 'NV: naamloze vennootschap (public company). VPB 19%/25.8%. Kapitaal minimum 45000 EUR. BTW 21%. Jaarrekening gepubliceerd verplicht.'),

('NL-VOF', 'NL',
 true, 'Geen drempel', 21, '6%, 0%',
 'IB_transparant', ARRAY['IB_transparant'],
 NULL, 'IB Box 1: 36.97-49.5% (vennoten)', NULL, 'Box 1: 36.97-49.5%',
 'ZZP-er variabel', 'N/A',
 'Geen minimum', false, NULL,
 'Aangifte IB per vennoot, BTW per kwartaal',
 'Belastingdienst', 'https://www.belastingdienst.nl',
 '2025-01-01', NULL, '2026-02-15',
 'VOF: vennootschap onder firma, fiscale transparantie. IB Box 1 vennoten 36.97-49.5%. BTW 21%. Geen kapitaal minimum.'),

('NL-EEN', 'NL',
 true, 'Geen drempel', 21, '6%, 0%',
 'IB_Box_1', ARRAY['IB_Box_1','zelfstandigenaftrek'],
 NULL, 'IB Box 1: 36.97-49.5%', NULL, NULL,
 'ZZP-er: geen werkgeverslasten', 'N/A',
 'N/A', false, 'Zelfstandigenaftrek mogelijk (2025: ~5030 EUR)',
 'Aangifte IB jaarlijks, BTW per kwartaal',
 'Belastingdienst', 'https://www.belastingdienst.nl',
 '2025-01-01', NULL, '2026-02-15',
 'Eenmanszaak: IB Box 1 36.97-49.5%. Zelfstandigenaftrek ~5030 EUR (2025). BTW 21%, geen drempel. Geen werkgeverslasten (ZZP).'),

('NL-MED', 'NL',
 true, 'Geen drempel', 21, '6%, 0%',
 'IB_Box_1', ARRAY['IB_Box_1','zelfstandigenaftrek'],
 NULL, 'IB Box 1: 36.97-49.5%', NULL, NULL,
 'ZZP-er: BIG-register verplicht', 'N/A',
 'N/A', false, NULL,
 'Aangifte IB jaarlijks, BTW per kwartaal of vrijstelling',
 'Belastingdienst', 'https://www.belastingdienst.nl',
 '2025-01-01', NULL, '2026-02-15',
 'Medicus: vrij beroep, IB Box 1 36.97-49.5%. BIG-register verplicht. BTW 21% of vrijstelling (gezondheidszorg). Zelfstandigenaftrek mogelijk.'),

('NL-STICHT', 'NL',
 false, 'N/A (indien niet-commercieel)', 21, '6%, 0%',
 'Vrijstelling', ARRAY['Vrijstelling','VPB_indien_commercieel'],
 '0% (niet-commercieel)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'Geen', false, 'Stichting ANBI: fiscale voordelen',
 'Geen indien niet-commercieel. Indien commercieel: VPB + BTW',
 'Belastingdienst', 'https://www.belastingdienst.nl',
 '2025-01-01', NULL, '2026-02-15',
 'Stichting: vrijgesteld indien niet-commercieel. ANBI-status: fiscale voordelen. Indien commercieel: VPB 19%/25.8%, BTW 21%.'),

('NL-COOP', 'NL',
 true, 'Geen drempel', 21, '6%, 0%',
 'Vennootschapsbelasting', ARRAY['Vennootschapsbelasting'],
 '19% tot 200000 EUR, 25.8% boven', NULL, '33% (2025), 36% (vanaf 2025)', 'Box 1: 36.97-49.5%',
 'AWf 2.74-7.74%', 'Variabel',
 'Variabel', false, NULL,
 'Aangifte VPB, BTW per kwartaal',
 'Belastingdienst', 'https://www.belastingdienst.nl',
 '2025-01-01', NULL, '2026-02-15',
 'Coöperatie: VPB 19% tot 200k EUR, 25.8% boven. BTW 21%. Geen bijzondere fiscale voordelen. AWf werkgeverslasten 2.74-7.74%.');

-- ============================================================================
-- SWEDEN (6 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('SE-AB', 'SE',
 false, '120000 SEK (från 2025)', 25, '12%, 6% (mat från 04/2026 tillfälligt till 12/2027)',
 'Bolagsskatt', ARRAY['Bolagsskatt'],
 '20.6%', NULL, '30% källskatt', 'Kommunalskatt 29-35% + statlig 20% över ~615000 SEK',
 '31.42% (10.21% över 67 år från 2026)', 'Inkluderat i system',
 '25000 SEK', false, NULL,
 'Bolagsdeklaration årlig, moms kvartalsvis, arbetsgivardeklaration månatlig',
 'Skatteverket', 'https://www.skatteverket.se',
 '2025-01-01', NULL, '2026-02-15',
 'AB: aktiebolag. Bolagsskatt 20.6%. Utdelning 30% källskatt. Moms 25%, gräns 120k SEK (från 2025). Aktiekapital 25000 SEK. Arbetsgivaravgift 31.42%.'),

('SE-AB-PUB', 'SE',
 true, 'Ingen gräns', 25, '12%, 6%',
 'Bolagsskatt', ARRAY['Bolagsskatt'],
 '20.6%', NULL, '30% källskatt', 'Kommunalskatt 29-35% + statlig 20%',
 '31.42%', 'Inkluderat',
 '500000 SEK', false, NULL,
 'Bolagsdeklaration, moms kvartalsvis, årsredovisning publicerad',
 'Skatteverket', 'https://www.skatteverket.se',
 '2025-01-01', NULL, '2026-02-15',
 'Publikt AB: börsnoterat aktiebolag. Bolagsskatt 20.6%. Kapital minimum 500000 SEK. Moms 25%, ingen gräns. Årsredovisning publicerad.'),

('SE-EF', 'SE',
 false, '120000 SEK', 25, '12%, 6%',
 'Inkomstskatt', ARRAY['Inkomstskatt'],
 NULL, 'Kommunalskatt 29-35% + statlig 20% över ~615000 SEK', NULL, NULL,
 'Egenavgifter ~28.97% (enskild näringsidkare)', 'N/A',
 'Inget', false, NULL,
 'Självdeklaration (INK2), moms kvartalsvis',
 'Skatteverket', 'https://www.skatteverket.se',
 '2025-01-01', NULL, '2026-02-15',
 'EF: enskild firma. Inkomstskatt kommunal 29-35% + statlig 20% över ~615k SEK. Egenavgifter ~28.97%. Moms 25%, gräns 120k SEK.'),

('SE-MED', 'SE',
 false, '120000 SEK', 25, '12%, 6%',
 'Inkomstskatt', ARRAY['Inkomstskatt'],
 NULL, 'Kommunalskatt 29-35% + statlig 20%', NULL, NULL,
 'Egenavgifter ~28.97%', 'N/A',
 'N/A', false, NULL,
 'Självdeklaration, moms kvartalsvis eller momsbefriad',
 'Skatteverket', 'https://www.skatteverket.se',
 '2025-01-01', NULL, '2026-02-15',
 'Läkare: fritt yrke, inkomstskatt kommunal + statlig. Egenavgifter ~28.97%. Moms 25% eller befriad (sjukvård). Gräns 120k SEK.'),

('SE-IDEELL', 'SE',
 false, 'N/A (om icke-kommersiell)', 25, '12%, 6%',
 'Skattefrihet', ARRAY['Skattefrihet','Bolagsskatt_om_kommersiell'],
 '0% (icke-kommersiell)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'Inget', false, 'Ideell förening, skattefrihet vid icke-kommersiell verksamhet',
 'Ingen vid icke-kommersiell. Vid kommersiell: bolagsdeklaration + moms',
 'Skatteverket', 'https://www.skatteverket.se',
 '2025-01-01', NULL, '2026-02-15',
 'Ideell förening: skattefri om icke-kommersiell. Vid kommersiell verksamhet: bolagsskatt 20.6%, moms 25%.'),

('SE-EKFOR', 'SE',
 true, 'Ingen gräns', 25, '12%, 6%',
 'Bolagsskatt', ARRAY['Bolagsskatt'],
 '20.6%', NULL, '30% källskatt', 'Kommunalskatt 29-35% + statlig 20%',
 '31.42%', 'Inkluderat',
 'Variabel', false, NULL,
 'Bolagsdeklaration årlig, moms kvartalsvis',
 'Skatteverket', 'https://www.skatteverket.se',
 '2025-01-01', NULL, '2026-02-15',
 'Ekonomisk förening: bolagsskatt 20.6%, moms 25% ingen gräns. Arbetsgivaravgift 31.42%. Utdelning 30% källskatt.');

-- ============================================================================
-- DENMARK (6 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('DK-APS', 'DK',
 false, '50000 DKK', 25, '0% (kun få kategorier)',
 'Selskabsskat', ARRAY['Selskabsskat'],
 '22%', NULL, '42% (individuel)', 'Bundskat 12.02% + kommuneskat ~25% + AM-bidrag 8%',
 'ATP 2376 DKK/år, AUB 2700 DKK/år, FIB 546 DKK/år', 'AM-bidrag 8% (trækkes af bruttoløn)',
 '40000 DKK (reduceres fra 2025)', false, NULL,
 'Selvangivelse selskabsskat årlig, moms kvartalsvis, årsrapport',
 'Skattestyrelsen', 'https://skat.dk',
 '2025-01-01', NULL, '2026-02-15',
 'ApS: anpartsselskab. Selskabsskat 22%. Moms 25%, tærskel 50k DKK. Kapital 40k DKK (reduceres 2025). ATP 2376 DKK/år, AUB 2700 DKK/år.'),

('DK-AS', 'DK',
 true, 'Ingen tærskel', 25, '0%',
 'Selskabsskat', ARRAY['Selskabsskat'],
 '22%', NULL, '42% (individuel)', 'Bundskat 12.02% + kommuneskat ~25% + AM-bidrag 8%',
 'ATP 2376 DKK/år, AUB 2700 DKK/år, FIB 546 DKK/år', 'AM-bidrag 8%',
 '400000 DKK', false, NULL,
 'Selvangivelse selskabsskat, moms kvartalsvis, årsrapport publiceret',
 'Skattestyrelsen', 'https://skat.dk',
 '2025-01-01', NULL, '2026-02-15',
 'A/S: aktieselskab (public). Selskabsskat 22%. Kapital 400k DKK. Moms 25%, ingen tærskel. Årsrapport publiceret obligatorisk.'),

('DK-EV', 'DK',
 false, '50000 DKK', 25, '0%',
 'Personlig indkomstskat', ARRAY['Personlig_indkomstskat'],
 NULL, 'Bundskat 12.02% + kommuneskat ~25% + topskat 15% over ~622000 DKK + AM-bidrag 8%', NULL, NULL,
 'Selvstændig: ingen arbejdsgiverbidrag', 'N/A',
 'Intet', false, NULL,
 'Selvangivelse personlig indkomst, moms kvartalsvis',
 'Skattestyrelsen', 'https://skat.dk',
 '2025-01-01', NULL, '2026-02-15',
 'Enkeltmandsvirksomhed: personlig indkomstskat (bundskat 12.02% + kommuneskat ~25% + topskat 15% + AM-bidrag 8%). Moms 25%, tærskel 50k DKK.'),

('DK-MED', 'DK',
 false, '50000 DKK', 25, '0%',
 'Personlig indkomstskat', ARRAY['Personlig_indkomstskat'],
 NULL, 'Bundskat 12.02% + kommuneskat ~25% + topskat 15% + AM-bidrag 8%', NULL, NULL,
 'Selvstændig: egen pensionsordning', 'N/A',
 'N/A', false, NULL,
 'Selvangivelse personlig indkomst, moms kvartalsvis eller momsfri',
 'Skattestyrelsen', 'https://skat.dk',
 '2025-01-01', NULL, '2026-02-15',
 'Læge: liberal profession, personlig indkomstskat. Moms 25% eller momsfri (sundhedsydelser). Tærskel 50k DKK. Egen pensionsordning.'),

('DK-FORENING', 'DK',
 false, 'N/A (hvis ikke-kommerciel)', 25, '0%',
 'Skattefritagelse', ARRAY['Skattefritagelse','Selskabsskat_hvis_kommerciel'],
 '0% (ikke-kommerciel)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'Intet', false, 'Forening, skattefritagelse hvis ikke-kommerciel',
 'Ingen hvis ikke-kommerciel. Hvis kommerciel: selskabsskat + moms',
 'Skattestyrelsen', 'https://skat.dk',
 '2025-01-01', NULL, '2026-02-15',
 'Forening: skattefri hvis ikke-kommerciel. Ved kommerciel aktivitet: selskabsskat 22%, moms 25%.'),

('DK-AMBA', 'DK',
 true, 'Ingen tærskel', 25, '0%',
 'Selskabsskat', ARRAY['Selskabsskat'],
 '22%', NULL, '42% (individuel)', 'Bundskat 12.02% + kommuneskat ~25% + AM-bidrag 8%',
 'ATP 2376 DKK/år, AUB 2700 DKK/år', 'AM-bidrag 8%',
 'Variabel', false, NULL,
 'Selvangivelse selskabsskat, moms kvartalsvis',
 'Skattestyrelsen', 'https://skat.dk',
 '2025-01-01', NULL, '2026-02-15',
 'A.m.b.a.: andelsselskab med begrænset ansvar. Selskabsskat 22%. Moms 25%, ingen tærskel. ATP/AUB standard arbejdsgiverbidrag.');

-- ============================================================================
-- FINLAND (6 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('FI-OY', 'FI',
 false, '20000 EUR (från 2025)', 25.5, '13.5% (från 2026, tidigare 14%), 10%',
 'Yhteisövero', ARRAY['Yhteisövero'],
 '20%', NULL, '85% beskattas 30% (upp till 30k EUR) / 34% (över)', 'Progressiv kommunalskatt 12-22% + kyrkoskatt ~1-2%',
 '17.1% TyEL (2026)', '7.3% TyEL (2026)',
 '2500 EUR (avskaffat 2019, nu 0 EUR)', false, 'Corporate tax kan vara 22% från 2026 (källkonflikt)',
 'Yhteisöveroilmoitus årlig, ALV kvartalsvis, TyEL månatlig',
 'Verohallinto', 'https://www.vero.fi',
 '2025-01-01', NULL, '2026-02-15',
 'Oy: osakeyhtiö. Yhteisövero 20% (konflikt: 22% från 2026 enligt vissa källor). ALV 25.5%, tröskeln 20k EUR. TyEL arbetsgivare 17.1%, anställd 7.3% (2026).'),

('FI-OYJ', 'FI',
 true, 'Ingen tröskel', 25.5, '13.5% (2026), 10%',
 'Yhteisövero', ARRAY['Yhteisövero'],
 '20%', NULL, '85% beskattas 30-34%', 'Progressiv 12-22%',
 '17.1% TyEL (2026)', '7.3% TyEL (2026)',
 '80000 EUR', false, NULL,
 'Yhteisöveroilmoitus, ALV kvartalsvis, årsberättelse publicerad',
 'Verohallinto', 'https://www.vero.fi',
 '2025-01-01', NULL, '2026-02-15',
 'Oyj: julkinen osakeyhtiö (börsnoterad). Yhteisövero 20%. Kapital 80k EUR. ALV 25.5%, ingen tröskel. TyEL 17.1%/7.3% (2026).'),

('FI-TMI', 'FI',
 false, '20000 EUR', 25.5, '13.5% (2026), 10%',
 'Ansiotuloverotus', ARRAY['Ansiotuloverotus'],
 NULL, 'Kommunalskatt 12-22% + statlig progressiv 12-31.25% + kyrkoskatt ~1-2%', NULL, NULL,
 'YEL 24.4% (2026)', 'N/A',
 'N/A', false, NULL,
 'Veroilmoitus (lomake 2), ALV kvartalsvis, YEL',
 'Verohallinto', 'https://www.vero.fi',
 '2025-01-01', NULL, '2026-02-15',
 'TMI: toiminimi (enskild firma). Ansiotuloverotus kommunal 12-22% + statlig 12-31.25%. YEL 24.4% (2026). ALV 25.5%, tröskel 20k EUR.'),

('FI-MED', 'FI',
 false, '20000 EUR', 25.5, '13.5% (2026), 10%',
 'Ansiotuloverotus', ARRAY['Ansiotuloverotus'],
 NULL, 'Kommunalskatt 12-22% + statlig 12-31.25%', NULL, NULL,
 'YEL 24.4% (2026)', 'N/A',
 'N/A', false, NULL,
 'Veroilmoitus, ALV kvartalsvis eller befriad (hälsovård)',
 'Verohallinto', 'https://www.vero.fi',
 '2025-01-01', NULL, '2026-02-15',
 'Lääkäri: liberal profession, ansiotuloverotus kommunal + statlig. YEL 24.4% (2026). ALV 25.5% eller befriad (hälsovård). Tröskel 20k EUR.'),

('FI-YHD', 'FI',
 false, 'N/A (om icke-kommersiell)', 25.5, '13.5% (2026), 10%',
 'Skattefrihet', ARRAY['Skattefrihet','Yhteisövero_om_kommersiell'],
 '0% (icke-kommersiell)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'Inget', false, 'Yhdistys, skattefrihet vid icke-kommersiell verksamhet',
 'Ingen vid icke-kommersiell. Vid kommersiell: yhteisöveroilmoitus + ALV',
 'Verohallinto', 'https://www.vero.fi',
 '2025-01-01', NULL, '2026-02-15',
 'Yhdistys: förening, skattefri om icke-kommersiell. Vid kommersiell verksamhet: yhteisövero 20%, ALV 25.5%.'),

('FI-OSK', 'FI',
 true, 'Ingen tröskel', 25.5, '13.5% (2026), 10%',
 'Yhteisövero', ARRAY['Yhteisövero'],
 '20%', NULL, '85% beskattas 30-34%', 'Kommunalskatt 12-22%',
 '17.1% TyEL (2026)', '7.3% TyEL (2026)',
 'Variabel', false, NULL,
 'Yhteisöveroilmoitus årlig, ALV kvartalsvis',
 'Verohallinto', 'https://www.vero.fi',
 '2025-01-01', NULL, '2026-02-15',
 'Osuuskunta: kooperativ. Yhteisövero 20%. ALV 25.5%, ingen tröskel. TyEL arbetsgivare 17.1%, anställd 7.3% (2026).');

-- ============================================================================
-- NORWAY (6 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('NO-AS', 'NO',
 false, '50000 NOK', 25, '15%, 12%, 0%',
 'Selskapsskatt', ARRAY['Selskapsskatt'],
 '22%', NULL, 'Variabel (inntektsskatt på mottaker)', 'Trinn 1-5: 1.7-17.4% + trinnskatt',
 '14.1%', '7.6% (2026)',
 '30000 NOK', false, NULL,
 'Selvangivelse selskapsskatt årlig, MVA per termin (2/6 ganger/år), a-melding månatlig',
 'Skatteetaten', 'https://www.skatteetaten.no',
 '2025-01-01', NULL, '2026-02-15',
 'AS: aksjeselskap. Selskapsskatt 22%. MVA 25%, terskelen 50k NOK. Kapital 30k NOK. Arbeidsgiveravgift 14.1%, ansatt 7.6% (2026).'),

('NO-ASA', 'NO',
 true, 'Ingen terskel', 25, '15%, 12%, 0%',
 'Selskapsskatt', ARRAY['Selskapsskatt'],
 '22%', NULL, 'Variabel', 'Trinn 1-5: 1.7-17.4%',
 '14.1%', '7.6% (2026)',
 '1000000 NOK', false, NULL,
 'Selvangivelse selskapsskatt, MVA per termin, årsregnskap publisert',
 'Skatteetaten', 'https://www.skatteetaten.no',
 '2025-01-01', NULL, '2026-02-15',
 'ASA: allmennaksjeselskap (public). Selskapsskatt 22%. Kapital 1M NOK. MVA 25%, ingen terskel. Årsregnskap publisert obligatorisk.'),

('NO-ENK', 'NO',
 false, '50000 NOK', 25, '15%, 12%, 0%',
 'Personinntektsskatt', ARRAY['Personinntektsskatt'],
 NULL, 'Trinn 1-5: 1.7-17.4% + trinnskatt (22% over ~208050 NOK) + kommuneskatt ~22%', NULL, NULL,
 'Selvstendig: trygdeavgift 10.9%', 'N/A',
 'Ingen', false, NULL,
 'Selvangivelse personinntekt, MVA per termin',
 'Skatteetaten', 'https://www.skatteetaten.no',
 '2025-01-01', NULL, '2026-02-15',
 'ENK: enkeltpersonforetak. Personinntektsskatt trinnskatt + kommuneskatt ~22%. Trygdeavgift 10.9% (selvstendig). MVA 25%, terskel 50k NOK.'),

('NO-MED', 'NO',
 false, '50000 NOK', 25, '15%, 12%, 0%',
 'Personinntektsskatt', ARRAY['Personinntektsskatt'],
 NULL, 'Trinnskatt + kommuneskatt ~22%', NULL, NULL,
 'Trygdeavgift 10.9%', 'N/A',
 'N/A', false, NULL,
 'Selvangivelse personinntekt, MVA per termin eller fritak',
 'Skatteetaten', 'https://www.skatteetaten.no',
 '2025-01-01', NULL, '2026-02-15',
 'Lege: liberal profesjon, personinntektsskatt trinnskatt + kommuneskatt. Trygdeavgift 10.9%. MVA 25% eller fritak (helsetjenester). Terskel 50k NOK.'),

('NO-FOR', 'NO',
 false, 'N/A (hvis ikke-kommersielle)', 25, '15%, 12%, 0%',
 'Skattefritak', ARRAY['Skattefritak','Selskapsskatt_hvis_kommersiell'],
 '0% (ikke-kommersiell)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'Ingen', false, 'Forening, skattefritak ved ikke-kommersiell virksomhet',
 'Ingen hvis ikke-kommersiell. Hvis kommersiell: selskapsskatt + MVA',
 'Skatteetaten', 'https://www.skatteetaten.no',
 '2025-01-01', NULL, '2026-02-15',
 'Forening: skattefri om ikke-kommersiell. Ved kommersiell virksomhet: selskapsskatt 22%, MVA 25%.'),

('NO-SA', 'NO',
 true, 'Ingen terskel', 25, '15%, 12%, 0%',
 'Selskapsskatt', ARRAY['Selskapsskatt'],
 '22%', NULL, 'Variabel', 'Trinnskatt + kommuneskatt',
 '14.1%', '7.6% (2026)',
 'Variabel', false, NULL,
 'Selvangivelse selskapsskatt årlig, MVA per termin',
 'Skatteetaten', 'https://www.skatteetaten.no',
 '2025-01-01', NULL, '2026-02-15',
 'SA: samvirkeforetak (kooperativ). Selskapsskatt 22%. MVA 25%, ingen terskel. Arbeidsgiveravgift 14.1%, ansatt 7.6% (2026).');

-- ============================================================================
-- ICELAND (6 forme juridice)
-- ============================================================================

INSERT INTO legal_form_tax_info (
  legal_form_code, country_code,
  vat_required, vat_threshold, vat_rate_standard, vat_rate_reduced,
  default_tax_regime, tax_regime_options,
  corporate_tax_rate, income_tax_rate, dividend_tax_rate, salary_tax_rate,
  social_contributions_employer, social_contributions_employee,
  min_capital, offshore_eligible, special_tax_status,
  fiscal_reporting, fiscal_authority, fiscal_authority_url,
  valid_from, valid_until, last_verified, notes
) VALUES
('IS-EHF', 'IS',
 true, 'Enginn þröskuldur', 24, '11%',
 'Tekjuskattur lögaðila', ARRAY['Tekjuskattur_lögaðila'],
 '20%', NULL, 'Variabel', 'Tekjuskattur einstaklinga 31.45-46.25%',
 '11.5% (lífeyrissjóður)', '4% (lífeyrissjóður)',
 '500000 ISK', false, NULL,
 'Skattframtal lögaðila árlega, VSK ársfjórðungslega, staðgreiðsla mánaðarlega',
 'Ríkisskattstjóri', 'https://www.rsk.is',
 '2025-01-01', NULL, '2026-02-15',
 'EHF: einkahlutafélag. Tekjuskattur 20%. VSK 24%, enginn þröskuldur. Hlutafé 500k ISK. Lífeyrissjóður vinnuveitandi 11.5%, starfsmaður 4%.'),

('IS-HF', 'IS',
 true, 'Enginn þröskuldur', 24, '11%',
 'Tekjuskattur lögaðila', ARRAY['Tekjuskattur_lögaðila'],
 '20%', NULL, 'Variabel', 'Tekjuskattur 31.45-46.25%',
 '11.5%', '4%',
 '4000000 ISK', false, NULL,
 'Skattframtal lögaðila, VSK ársfjórðungslega, ársreikningur birtur',
 'Ríkisskattstjóri', 'https://www.rsk.is',
 '2025-01-01', NULL, '2026-02-15',
 'HF: hlutafélag (public). Tekjuskattur 20%. Hlutafé 4M ISK. VSK 24%, enginn þröskuldur. Ársreikningur birtur skylda.'),

('IS-EINST', 'IS',
 true, 'Enginn þröskuldur', 24, '11%',
 'Tekjuskattur einstaklinga', ARRAY['Tekjuskattur_einstaklinga'],
 NULL, 'Tekjuskattur 31.45-46.25%', NULL, NULL,
 'Sjálfstætt starfandi: lífeyrissjóður ~12%', 'N/A',
 'Ekkert', false, NULL,
 'Skattframtal einstaklinga, VSK ársfjórðungslega',
 'Ríkisskattstjóri', 'https://www.rsk.is',
 '2025-01-01', NULL, '2026-02-15',
 'Einstaklingsfyrirtæki: tekjuskattur 31.45-46.25%. Lífeyrissjóður ~12% (sjálfstætt starfandi). VSK 24%, enginn þröskuldur.'),

('IS-MED', 'IS',
 true, 'Enginn þröskuldur', 24, '11%',
 'Tekjuskattur einstaklinga', ARRAY['Tekjuskattur_einstaklinga'],
 NULL, 'Tekjuskattur 31.45-46.25%', NULL, NULL,
 'Lífeyrissjóður ~12%', 'N/A',
 'N/A', false, NULL,
 'Skattframtal einstaklinga, VSK ársfjórðungslega eða undanþága',
 'Ríkisskattstjóri', 'https://www.rsk.is',
 '2025-01-01', NULL, '2026-02-15',
 'Læknir: frjálst starf, tekjuskattur 31.45-46.25%. Lífeyrissjóður ~12%. VSK 24% eða undanþága (heilbrigðisþjónusta). Enginn þröskuldur.'),

('IS-FELAG', 'IS',
 false, 'N/A (ef ekki viðskiptalegt)', 24, '11%',
 'Skattfrelsi', ARRAY['Skattfrelsi','Tekjuskattur_ef_viðskiptalegt'],
 '0% (ekki viðskiptalegt)', NULL, NULL, NULL,
 'N/A', 'N/A',
 'Ekkert', false, 'Félag, skattfrelsi við ekki-viðskiptalega starfsemi',
 'Ekkert ef ekki viðskiptalegt. Ef viðskiptalegt: tekjuskattur + VSK',
 'Ríkisskattstjóri', 'https://www.rsk.is',
 '2025-01-01', NULL, '2026-02-15',
 'Félag: skattfrjálst ef ekki viðskiptalegt. Við viðskiptalega starfsemi: tekjuskattur 20%, VSK 24%.'),

('IS-SAMV', 'IS',
 true, 'Enginn þröskuldur', 24, '11%',
 'Tekjuskattur lögaðila', ARRAY['Tekjuskattur_lögaðila'],
 '20%', NULL, 'Variabel', 'Tekjuskattur 31.45-46.25%',
 '11.5%', '4%',
 'Variabel', false, NULL,
 'Skattframtal lögaðila árlega, VSK ársfjórðungslega',
 'Ríkisskattstjóri', 'https://www.rsk.is',
 '2025-01-01', NULL, '2026-02-15',
 'Samvinnufélag: tekjuskattur 20%. VSK 24%, enginn þröskuldur. Lífeyrissjóður vinnuveitandi 11.5%, starfsmaður 4%.');

-- ============================================================================
-- VERIFICARE
-- ============================================================================

SELECT
  country_code,
  COUNT(*) as nr_forme
FROM legal_form_tax_info
WHERE country_code IN ('FR','IT','ES','PT','NL','SE','DK','FI','NO','IS')
GROUP BY country_code
ORDER BY country_code;

-- Expected result:
-- FR: 13
-- IT: 10
-- ES: 7
-- PT: 7
-- NL: 7
-- SE: 6
-- DK: 6
-- FI: 6
-- NO: 6
-- IS: 6
-- TOTAL: 74

-- ============================================================================
-- END OF FILE
-- ============================================================================
